version: "3.3"
services:
  webserver:
    image: nginx:1.25.4-alpine-slim
    container_name: proxy 
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  nginx:
    image: nginx:1.25.4-alpine-slim
    container_name: myweb
    restart: always
    volumes:
      - ./data/certbot/www:/var/www/certbot

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
